services:
  database:
    image: postgres:18-alpine
    container_name: lazybook_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lazybook_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:8-alpine
    container_name: lazybook_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
